config/routes.rb
Rails.application.routes.draw do
  resources :pops

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pop.rb
class Pop < ApplicationRecord
  before_save :check_exclusivity
  before_save :scrape_price

  def total
    self.ppg_price * self.quantity
  end

  def net
    net = ((self.ppg_price * self.quantity) - (self.amount_paid * self.quantity)).round(2)
    if net < 0
      "<span class='text-danger'>($#{net * -1})</span>".html_safe
    else
      "$#{net}".html_safe
    end
  end

  private

  def check_exclusivity
    if self.exclusivity.blank?
      self.exclusive = false
    else
      self.exclusive = true
    end
  end

  def scrape_price
    doc = Nokogiri::HTML(open(self.ppg_url))
    self.ppg_price = doc.at_css(".itmValue").text.strip.partition("$").last.partition(".").first
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/controllers/pops_controller.rb
class PopsController < ApplicationController
  before_action :set_pop, only: [ :show, :edit, :update, :destroy ]

  def index
    @pops = Pop.all
  end

  def show
  end

  def new
    @pop = Pop.new()
  end

  def create
    @pop = Pop.new(pop_params)
    if @pop.save
      redirect_to @pop, notice: "The Pop! has been successfully saved."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @pop.update_attributes(pop_params)
      redirect_to @pop, notice: "The Pop! was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @pop.destroy
    redirect_to @pops, notice: "The Pop! was successfully removed."
  end

  private

  def pop_params
    params.require(:pop).permit(:name, :number, :collection, :category, :exclusivity, :amount_paid, :quantity, :condition, :box_number, :notes, :ppg_url)
  end

  def set_pop
    @pop = Pop.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>My Pops</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The POP! Club</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
        <%= link_to "The POP! Club", root_url, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to_unless_current "Catalog", pops_path, class: "nav-link" do %>
                <%= link_to "Catalog", pops_path, class: "nav-link active" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/pops/_form.html.erb
<div class="row">
  <%= form_with model: @pop, local: true, class: "col s6 offset-s3" do |f| %>

    <div class="row">
      <div class="input-field col s9">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>
      <div class="input-field col s3">
        <%= f.label :number %>
        <%= f.text_field :number %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= f.label :exclusivity %>
        <%= f.text_field :exclusivity %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s6">
        <%= f.label :category %>
        <%= f.text_field :category %>
      </div>
      <div class="input-field col s6">
        <%= f.label :collection %>
        <%= f.text_field :collection %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s4">
        <%= f.label :amount_paid, "Amount Paid" %>
        <%= f.text_field :amount_paid %>
      </div>
      <div class="input-field col s4">
        <%= f.label :quantity %>
        <%= f.text_field :quantity %>
      </div>
      <div class="input-field col s4">
        <%= f.label :box_number, "Box Number" %>
        <%= f.text_field :box_number %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= f.label :notes %>
        <%= f.text_area :notes, class: "materialize-textarea" %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= f.label :ppg_url, "PPG URL" %>
        <%= f.text_field :ppg_url %>
      </div>
    </div>

    <%= f.submit class: "waves-effect waves-light btn" %>

  <% end %>
</div>

app/views/pops/edit.html.erb
<h4>Edit Pop</h4>
<hr>

<%= render partial: "form" %>

app/views/pops/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th class="center-align">Number</th>
      <th class="center-align">Quantity</th>
      <th class="center-align">Paid</th>
      <th class="center-align">Value</th>
      <th class="center-align">Total</th>
      <th class="center-align">Net</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pops.each do |pop| %>
      <tr>
        <td>
          <%= link_to pop.name, pop %>
          <% if pop.exclusive %>
            <span class="badge badge-primary text-right"><%= pop.exclusivity %></span>
          <% end %>
        </td>
        <td class="center-align">#<%= pop.number %></td>
        <td class="center-align"><%= pop.quantity %></td>
        <td class="center-align"><%= number_to_currency pop.amount_paid, precision: 0 %></td>
        <td class="center-align"><%= number_to_currency pop.ppg_price, precision: 0 %></td>
        <td class="center-align"><%= number_to_currency pop.total, precision: 0 %></td>
        <td class="center-align"><%= pop.net %></td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pops/new.html.erb
<h4>New Pop</h4>
<hr>

<%= render partial: "form" %>

app/views/pops/show.html.erb
<h3><%= @pop.name %> - <%= @pop.number %></h3>